language: node_js
node_js:
  - 'stable'
services:
  - mongodb
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: package install
      script:
        - yarn
        - cd client
        - yarn
    - stage: server and client tests
      script:
        - yarn test
