language: node_js
node_js:
  - 'node'
services:
  - mongodb
jobs:
  include:
    - stage: package install
    script:
      - yarn
      - cd client
      - yarn
    - stage: server and client tests
      - yarn test
